version: '3'

services:

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
      CASSANDRA_CLUSTER_NAME: cluster
      CASSANDRA_DC: we-dc1
      CASSANDRA_SEEDS: cassandra
    ports:
      - 9042:9042
    networks:
      - ecommerce-net

  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - ecommerce-net

  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper
    networks:
      - ecommerce-net

  mongo:
    image: mongo:3.4.14
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
