version: '3'

services:
  mongo:
    image: mongo:3.4.14
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    networks:
      - todo-service-net

networks:
  todo-service-net:
